baseurl = "https://moonlightmovement.github.io/"
metaDataFormat = "yaml"
title = "Blist Multilingual Theme"
theme = "blist"

DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = true
[languages]
  [languages.en]
    contentDir = "content/en" #English
    weight = 1
    languageName = "English"
    [languages.en.params]
      introTitle = "Moonlight Movement"
      introSubtitle = "driving a four year strategy to stop democratic backsliding and reclaim and rebuild our democracy relying on strategies of creative constructive intervention"
      introPhoto = "/stopcoup.PNG"
      logo = "/blist-logo.png"
    [[languages.en.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 1

    [[languages.en.menu.main]]
        name = "Mission"
        url = "page/about/"
        weight = 2

    [[languages.en.menu.main]]
        name = "Tags"
        url = "tags"
        weight = 3

    [[languages.en.menu.main]]
        name = "Top Post"
        url = "/en/blog/emoji-support/"
        weight = 4

  [languages.de]
    contentDir = "content/de" # Deutsch
    weight = 2
    languageName = "Deutsch"
    title = "Blist (mehrsprachig)"
    description = "Modernes Blog-Theme für Ihre Hugo-Site."
    [languages.de.params]
      introTitle = "Hallo, ich bin Katheryn Fox"
      introSubtitle = "26-jährige Junior-Entwicklerin, die Spaß an sozialen Kartenspielen, Bloggen und Malen hat"
      introPhoto = "/picture.jpg"
      logo = "/blist-logo-de.png"
    [[languages.de.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 1

    [[languages.de.menu.main]]
        name = "Über mich"
        url = "page/about/"
        weight = 2

    [[languages.de.menu.main]]
        name = "Tags"
        url = "tags"
        weight = 3

  [languages.dy]
    contentDir = "content/dy" #Example language
    weight = 3
    languageName = "Test Language"

[params]
  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = true

  # Custom copyright - optional
  copyright = "Copyright © 2021 - Katheryn Fox · All rights reserved"
  favicon = "/favicon.svg"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-100"

  # The page bundle that is shown on the front page
  frontBundle = "blog"

[params.homepage.social]
  # Global params xommon for both languages
  title = "Follow me"
  description = "We're on X, Bluesky, and Instagram"
  twitter = "https://x.com/projmoonshot"
  instagram = "https://www.instagram.com/projmoonshot/"
  medium = "https://bsky.app/profile/projectmoonshot.bsky.social"
  

[[menu.main]]
  name = "About"
  url = "/about"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
